// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: proto/tictactoe.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TicTacToeClient is the client API for TicTacToe service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TicTacToeClient interface {
	InitialState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Board, error)
}

type ticTacToeClient struct {
	cc grpc.ClientConnInterface
}

func NewTicTacToeClient(cc grpc.ClientConnInterface) TicTacToeClient {
	return &ticTacToeClient{cc}
}

func (c *ticTacToeClient) InitialState(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*Board, error) {
	out := new(Board)
	err := c.cc.Invoke(ctx, "/tictactoe.TicTacToe/InitialState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TicTacToeServer is the server API for TicTacToe service.
// All implementations must embed UnimplementedTicTacToeServer
// for forward compatibility
type TicTacToeServer interface {
	InitialState(context.Context, *emptypb.Empty) (*Board, error)
	mustEmbedUnimplementedTicTacToeServer()
}

// UnimplementedTicTacToeServer must be embedded to have forward compatible implementations.
type UnimplementedTicTacToeServer struct {
}

func (UnimplementedTicTacToeServer) InitialState(context.Context, *emptypb.Empty) (*Board, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitialState not implemented")
}
func (UnimplementedTicTacToeServer) mustEmbedUnimplementedTicTacToeServer() {}

// UnsafeTicTacToeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TicTacToeServer will
// result in compilation errors.
type UnsafeTicTacToeServer interface {
	mustEmbedUnimplementedTicTacToeServer()
}

func RegisterTicTacToeServer(s grpc.ServiceRegistrar, srv TicTacToeServer) {
	s.RegisterService(&TicTacToe_ServiceDesc, srv)
}

func _TicTacToe_InitialState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TicTacToeServer).InitialState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tictactoe.TicTacToe/InitialState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TicTacToeServer).InitialState(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// TicTacToe_ServiceDesc is the grpc.ServiceDesc for TicTacToe service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TicTacToe_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tictactoe.TicTacToe",
	HandlerType: (*TicTacToeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitialState",
			Handler:    _TicTacToe_InitialState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tictactoe.proto",
}
